name: Test

on:
  schedule:
    - cron: "38 * * * *"
  workflow_dispatch:
  push:
    branches:
      - latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests without failing on warnings
        run: npm test

      - name: Run tests with failing on warnings
        run: npm run test:fail-on-console
